footer:
  jobs: ["Wegbegleitung", "Dentosophie", "Cranio-Sacral Therapie"]
  city: "Habkern"
  city_nearby: "Interlaken"
  canton: "Berner Oberland"
  country: "Schweiz"
  first_name: "Pia"
  last_name: "Kammer"

url:
  impressum: "/output/impressum.html"
  dsb: "/output/dsb.html"