this_site:
  name: "about"
  title: "Ein wenig über mich"
  tab_title: "Über mich"
  main_class: "section"

background_img:
  style: "opacity: 0.2;"
  src: "../assets/nature/photo_3_2025-07-08_07-45-46.jpg"

#background_img: false