# censored for usage with LLMs

personal:
  first_name: "Maria"
  last_name: "Mustermann"
  adress: "Strasse 1a"
  zip: "1234"
  city: "Ortschaft"
  city_nearby: "Umgebung"
  canton: "Kanton"
  country: "Schweiz"
  email: "info@email.ch"
  jobs: ["job1", "job2", "job3"]

links:
  dir: "../html"
  impressum: "impressum.html"
  dsb: "dsb.html"
  index: "index.html"

background_img:
  alt: "Hintergrundbild"
  class: "hero-background is-transparent"
  dir: "../assets"
  file: "flower-of-life.svg"

website:
  title: "Arbeitstitel"
  language: "de-CH"
  developer:
    name: "Schweizer"
    prename: "Hans"
    email: "none"

this_site:
  name: "none"
  main_class: "section"
  content_class: "hero-body is-fullheight has-background"
