personal:
  first_name: "Pia"
  last_name: "Kammer"
  adress: "Hohlgässli 367b"
  zip: "3804"
  city: "Habkern"
  city_nearby: "Interlaken"
  canton: "Berner Oberland"
  country: "Schweiz"
  email: "info@dentosophia.ch"
  jobs: ["Wegbegleitung", "Dentosophie", "Cranio-Sacral Therapie"]

links:
  dir: "../html"
  impressum: "impressum.html"
  dsb: "dsb.html"
  index: "index.html"
  about: "about.html"
  kontakt: "kontakt.html"
  material: "material.html"
  kosten: "kosten.html"
  dentosophie: "dentosophie.html"
  cranio: "cranio.html"

background_img:
  alt: ""
  class: "hero-background is-transparent"
  style: "opacity: 0.1;"
  src: "../assets/flower-of-life.svg"
  role: "img"         # alternative: presentation, ...
  aria-hidden: "true"
  loading: "lazy"
  decoding: "async"   # browser decodes image in parallel. Good for png and svg.

website:
  title: "Dentosophia"
  language: "de-CH"
  developer:
    name: "Zbinden"
    prename: "Simon Michael"
    email: "none"

this_site:
  name: "none"
  description: ""
  keywords: ["Test1", "Test2", "Test3"]
  main_class: "hero-body"
  title: "None"
  main_class: "section"
  content_class: "container"
