personal:
  jobs: ["Wegbegleitung", "Dentosophie", "Cranio-Sacral Therapie"]
  city: "Habkern"
  city_nearby: "Interlaken"
  canton: "Berner Oberland"
  country: "Schweiz"
  first_name: "Pia"
  last_name: "Kammer"

links:
  dir: "../html"
  impressum: "impressum.html"
  dsb: "dsb.html"
  index: "index.html"